const hosting = "https://d3spngajmc7mtz.cloudfront.net/";

export const audioData = [
	{
		name: "Imagine",
        lesson: "Lesson 1",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2001.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	{
		name: "Imagine",
        lesson: "Lesson 2",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2002.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	{
		name: "Imagine",
        lesson: "Lesson 3",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2003.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	{
		name: "Imagine",
        lesson: "Lesson 4",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2004.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	
	{
		name: "What a wonderful world",
        lesson: "Lesson 1",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2005.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "What a wonderful world",
        lesson: "Lesson 2",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2006.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "What a wonderful world",
        lesson: "Lesson 3",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2007.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "What a wonderful world",
        lesson: "Lesson 4",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2008.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 1",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2009.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 2",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2010.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 3",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2011.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 4",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2012.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 1",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2013.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 2",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2014.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 3",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2015.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 4",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2016.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
]
export const audioData_Normal = [
	{
		name: "Imagine",
        lesson: "Lesson 1",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2001.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	{
		name: "Imagine",
        lesson: "Lesson 2",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2002.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	{
		name: "Imagine",
        lesson: "Lesson 3",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2003.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	{
		name: "Imagine",
        lesson: "Lesson 4",
        artist: "John Lenon",
        url:  `${hosting}English/LESSON%2004.mp3`,
        cover: `${hosting}img/1.jpeg`,
	},
	
	{
		name: "What a wonderful world",
        lesson: "Lesson 1",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2005.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "What a wonderful world",
        lesson: "Lesson 2",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2006.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "What a wonderful world",
        lesson: "Lesson 3",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2007.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "What a wonderful world",
        lesson: "Lesson 4",
        artist: "Louis Armstrong",
        url:  `${hosting}English/LESSON%2008.mp3`,
        cover: `${hosting}img/4.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 1",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2009.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 2",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2010.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 3",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2011.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Over the Rainbow",
		lesson: "Lesson 4",
		artist: "Judy Garland",
        url:  `${hosting}English/LESSON%2012.mp3`,
        cover: `${hosting}img/5.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 1",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2013.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 2",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2014.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 3",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2015.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
	{
		name: "Stayin' Alive",
		lesson: "Lesson 4",
		artist: "Bee Gees",
        url:  `${hosting}English/LESSON%2016.mp3`,
        cover: `${hosting}img/6.jpg`,
	},
]
